function MNQ_E_dialogue(data)

fh=figure('Name', 'Generate MNQ(r)',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.18,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1x',...
       'Position', [0.05 0.85 0.2 0.15]);
bragg1x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.05 0.58 0.2 0.25],...
        'String','50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1y',...
       'Position', [0.05 0.35 0.2 0.15]);
bragg1y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.05 0.08 0.2 0.25],...
        'String','50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2x',...
    'Position', [0.35 0.85 0.2 0.15]);  
bragg2x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.35 0.58 0.2 0.25],...
       'String','-50');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2y',...
       'Position', [0.35 0.35 0.2 0.15]);  
bragg2y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.35 0.08 0.2 0.25],...
        'String','50');
   
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Peak Width',...
       'Position', [0.65 0.85 0.2 0.15]);  
width = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.65 0.58 0.2 0.25],...
        'String','10');    
    
    
OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','Generate',...
       'units','normalized',...
       'Position',[0.65 0.32 0.2 0.2],...
       'Callback',@OK_Callback);

 done_but = uicontrol(fh,'Style','pushbutton',...
       'String','Done',...
       'units','normalized',...
       'Position',[0.65 0.08 0.2 0.2],...
       'Callback',@done_Callback);
  
%%%%%%%%%%%%%%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    function OK_Callback(hobject,eventdata)
        pt1(1) = str2num(get(bragg1x,'String'));
        pt1(2) = str2num(get(bragg1y,'String'));
        pt2(1) = str2num(get(bragg2x,'String'));
        pt2(2) = str2num(get(bragg2y,'String'));
        width_sz = str2num(get(width,'String'));
        MNQ_E(data,pt1,pt2,width_sz);        
    end
    function done_Callback(hObject,eventdata)       
        close(fh);
    end
end