function sym_map_dialogue(data)
fh=figure('Name', 'Symmmetrize Image',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.18,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');
    
    uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Vertical Axis',...
       'Position', [0.05 0.85 0.2 0.15]);
vert_chk = uicontrol(fh,'Style', 'checkbox',... 
       'units','normalized',...              
       'Position', [0.05 0.58 0.2 0.25]);

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Horizontal Axis',...
       'Position', [0.05 0.35 0.2 0.15]);
hor_chk = uicontrol(fh,'Style','checkbox',...
        'units','normalized',...
        'Position',[0.05 0.08 0.2 0.25]);        

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Diagonal Axis',...
    'Position', [0.35 0.85 0.2 0.15]);  
diag_chk = uicontrol(fh,'Style', 'checkbox',... 
       'units','normalized',...              
       'Position', [0.35 0.58 0.2 0.25]);     

OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','normalized',...
       'Position',[0.7 0.6 0.25 0.25],...
       'Callback',@OK_Callback);

 cancel_but = uicontrol(fh,'Style','pushbutton',...
       'String','Cancel',...
       'units','normalized',...
       'Position',[0.7 0.25 0.25 0.25],...
       'Callback',@cancel_Callback);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%FUNCTION CALLBACK%%%%%%%%%%%%%%%%%%%%%%%%
    function OK_Callback(hObject,eventdata)
        str = [];
        if ((get(vert_chk,'Value') == get(vert_chk,'Max')))
            str = [str 'v']
        end  
        if ((get(hor_chk,'Value') == get(hor_chk,'Max')))
            str = [str 'h']
        end 
        if ((get(diag_chk,'Value') == get(diag_chk,'Max')))
            str = [str 'd']
        end 
        if isempty(str)
            close(fh);
        else
            new_data = symmetrize_image(data,str);
            new_data.ave = [];
            new_data.var = [new_data.var '_sym_' str];
            new_data.ops{end+1} = ['Symmetrized Along ' str];
%             img_obj_viewer2(new_data);
            img_obj_viewer_test(new_data)
            display('New Data Created');
            close(fh);
        end
    end
    function cancel_Callback(hObject,eventdata)
        close(fh);
    end
end