function map = Peak_invert_dialogue(data,varargin)

pairs = varargin{1};

boxheight = 0.07;
boxspacing = boxheight*0.3;
fh=figure('Name', 'Invert Peak Options',...
    'units','normalized', ...
    'Position',[0.3,0.3,0.18,0.3],...
    'Color',[0.6 0.6 0.6],...
    'MenuBar', 'none',...
    'NumberTitle', 'off');%,...
%         'Resize','off');


str1 = 'real|imaginary|ampltude';
ft_type_pop = uicontrol(fh,'Style', 'popup',...
    'units','normalized',...
    'Value',1,...
    'String', str1,...
    'Position', [0.05 0.45 0.3 0.5]);

for pair = 1:pairs
    editx(pair) = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'position',[0.3 0.35+boxheight*(pairs-pair)*(1+boxspacing) 0.18 boxheight]);
    uicontrol(fh,'Style','text', 'units','normalized',...
        'position',[0.2 0.35+boxheight*(pairs-pair)*(1+boxspacing) 0.1 boxheight],...
        'String',['x' num2str(pair)]);
    edity(pair) = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'position',[0.6 0.35+boxheight*(pairs-pair)*(1+boxspacing) 0.18 boxheight]);
    uicontrol(fh,'Style','text', 'units','normalized',...
        'position',[0.5 0.35+boxheight*(pairs-pair)*(1+boxspacing) 0.1 boxheight],...
        'String',['y' num2str(pair)]);
end

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'position',[0.07 0.16 0.4 boxheight],...
    'String','sigma for Gauss mask');

sigma = uicontrol(fh,'Style','edit',...
    'units','normalized',...
    'position',[0.5 0.16 0.1 boxheight],...
    'String','5');


% edit_x1 = uicontrol(fh,'Style','edit',...
%     'units','normalized',...
%     'position',[0.6 0.35 0.25 0.25]);
% edit_y1 = uicontrol(fh,'Style','edit',...
%     'units','normalized',...
%     'position',[0.6 0.35 0.25 0.25]);
% edit_x2 = uicontrol(fh,'Style','edit',...
%     'units','normalized',...
%     'position',[0.6 0.35 0.25 0.25]);
% edit_y2 = uicontrol(fh,'Style','edit',...
%     'units','normalized',...
%     'position',[0.6 0.35 0.25 0.25]);


OK_but = uicontrol(fh,'Style','pushbutton',...
    'String','OK',...
    'units','normalized',...
    'Position',[0.7 0.1 0.25 0.15],...
    'Callback',@OK_Callback);

    function OK_Callback(hObject,eventdata)
        
        switch get(ft_type_pop,'Value')
            case 1
                type = 'real';
            case 2
                type = 'imag';
            case 3
                type = 'abs';
        end
        
        q=0;
        for k = 1:pairs
            q=q+1;
            x(q)= round(str2double(get(editx(k),'String')));
            q=q+1;
            x(q) = round(str2double(get(edity(k),'String')));
        end
        
        gauss_sigma = round(str2double(get(sigma,'String')));
        
        
        map = invert_peaks_function(data,type,gauss_sigma,x);
        close(fh)
    end
end

