% 2020-5-16 YXC


function [new_data,q0,p,theta,alpha,q_px] = Shear_correct_tetra_dialogue(data,varargin)



if nargin>1
    qvals = varargin{1};
    b1xtext = num2str(qvals(1,1));
    b1ytext = num2str(qvals(1,2));
    b2xtext = num2str(qvals(2,1));
    b2ytext = num2str(qvals(2,2));
else
    b1xtext = num2str(size(data.map,1)/5);
    b1ytext = b1xtext;
    b2xtext = b1xtext;
    b2ytext = b1xtext;
end


fh=figure('Name', 'Shear Correct for Tetragonal Lattice',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.3,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1x',...
       'Position', [0.05 0.85 0.12 0.15]);
bragg1x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.05 0.58 0.12 0.25],...
        'String',b1xtext);

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1y',...
       'Position', [0.05 0.35 0.12 0.15]);
bragg1y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.05 0.08 0.12 0.25],...
        'String',b1ytext);

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2x',...
    'Position', [0.25 0.85 0.12 0.15]);  
bragg2x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.25 0.58 0.12 0.25],...
       'String',b2xtext);

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2y',...
       'Position', [0.25 0.35 0.12 0.15]);  
bragg2y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.25 0.08 0.12 0.25],...
        'String',b2ytext);
   

    
OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','normalized',...
       'Position',[0.7 0.6 0.25 0.25],...
       'Callback',@OK_Callback);

 cancel_but = uicontrol(fh,'Style','pushbutton',...
       'String','Cancel',...
       'units','normalized',...
       'Position',[0.7 0.25 0.25 0.25],...
       'Callback',@cancel_Callback);
  
 uiwait(gcf); 
 
%%%%%%%%%%%%%%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    function OK_Callback(hobject,eventdata)
        q_px(1,1) = str2double(get(bragg1x,'String'));
        q_px(2,1) = str2double(get(bragg1y,'String'));
        q_px(1,2) = str2double(get(bragg2x,'String'));
        q_px(2,2) = str2double(get(bragg2y,'String'));

        [new_data,q0,p,theta,alpha] = shear_correct_ortho(data,q_px(:,1),q_px(:,2));
        close(fh);
    end
    function cancel_Callback(hObject,eventdata)       
        close(fh);
    end
end