% 2020/4/24 YXC
% in use with register_lattice_gui

function [leftorright,moveright,movedown]= XCorr_Movement_dialogue(sug_map,sug_moveright,sug_movedown)

col = [0.8 0.8 0.8];



fh = figure('Name', 'Change Pixel Dimensions',...
    'units','normalized', ...
    'Position',[0.3,0.3,0.2,0.1],...
    'Color',col,...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Resize','off');



uicontrol(fh,'Style','text',...
    'String','Move Map on the',...
    'units','normalized',...
    'BackgroundColor',col,...
    'Position', [0.15 0.75 0.3 0.2]);



mapchoie = uicontrol(fh,'Style','popupmenu',...
    'String','Left|Right',...
    'units','normalized',...
    'BackgroundColor',col,...
    'Value',sug_map,...
    'Position', [0.2 0.6 0.3 0.2]);




uicontrol(fh,'Style', 'text',...
    'units','normalized',...
    'String', 'Move right by:              Move Down by',...
    'BackgroundColor',col,...
    'Position', [0.1 0.25 0.5 0.2]);

editright= uicontrol(fh,'Style', 'edit',...
    'units','normalized',...
    'String', num2str(sug_moveright),...
    'Position', [0.1 0.1 0.2 0.2]);
editdown= uicontrol(fh,'Style', 'edit',...
    'units','normalized',...
    'String', num2str(sug_movedown),...
    'Position', [0.4 0.1 0.2 0.2]);

    
   
OK_but = uicontrol(fh,'Style','pushbutton',...
                          'String','OK',...
                          'units','normalized',...
                          'Position',[0.8 0.5 0.14 0.3],...
                          'Callback',(@OK_Callback));
cancel_but = uicontrol(fh,'Style','pushbutton',...
                          'String','Cancel',...
                          'units','normalized',...
                          'Position',[0.8 0.1 0.14 0.3],...
                          'Callback',(@cancel_Callback));
%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uiwait(gcf); 
%halt execution of STM_View until this function returns a file to open

function OK_Callback(hObject,eventdata)
   moveright = str2double(get(editright,'String'));
   movedown = str2double(get(editdown,'String'));
   leftorright = mapchoie.Value;
   close(fh);
end
    function cancel_Callback(hObject,eventdata)
        moveright= 0;
        movedown = 0;
        close(fh);
    end
end

    
