function LF_phase_gen_dialogue_hex(data,varargin)
fh=figure('Name', 'Bragg Peak Coordinates + Filter Width',...
        'units','normalized', ...
        'Position',[0.3,0.3,0.3,0.1],...
        'Color',[0.6 0.6 0.6],...
        'MenuBar', 'none',...
        'NumberTitle', 'off',...
        'Resize','off');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1x',...
       'Position', [0.05 0.85 0.12 0.15]);
bragg1x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.05 0.58 0.12 0.25],...
        'String','65');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q1y',...
       'Position', [0.05 0.35 0.12 0.15]);
bragg1y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.05 0.08 0.12 0.25],...
        'String','46');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2x',...
    'Position', [0.20 0.85 0.12 0.15]);  
bragg2x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.20 0.58 0.12 0.25],...
       'String','81');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q2y',...
       'Position', [0.20 0.35 0.12 0.15]);  
bragg2y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.20 0.08 0.12 0.25],...
        'String','56');
 
   
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q3x',...
    'Position', [0.35 0.85 0.12 0.15]);  
bragg3x = uicontrol(fh,'Style', 'edit',... 
       'units','normalized',...              
       'Position', [0.35 0.58 0.12 0.25],...
       'String','82');

uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Q3y',...
       'Position', [0.35 0.35 0.12 0.15]);  
bragg3y = uicontrol(fh,'Style','edit',...
        'units','normalized',...
        'Position',[0.35 0.08 0.12 0.25],...
        'String','75');


    
uicontrol(fh,'Style','text',...
    'units','normalized',...
    'String','Filter Width',...
    'Position', [0.50 0.55 0.12 0.15]);
%     'Position', [0.45 0.55 0.12 0.15]);

filt_width = uicontrol(fh,'Style','edit',...
    'units','normalized',...
    'Position',[0.50 0.25 0.12 0.25],...%     'Position',[0.45 0.25 0.12 0.25],...
    'String','3');
    
OK_but = uicontrol(fh,'Style','pushbutton',...
       'String','OK',...
       'units','normalized',...
       'Position',[0.7 0.6 0.25 0.25],...%        'Position',[0.7 0.6 0.25 0.25],...
       'Callback',@OK_Callback);

 cancel_but = uicontrol(fh,'Style','pushbutton',...
       'String','Cancel',...
       'units','normalized',...
       'Position',[0.7 0.25 0.25 0.25],...%        'Position',[0.7 0.25 0.25 0.25],...       
       'Callback',@cancel_Callback);
  
%%%%%%%%%%%%%%%%%%%%%%%%CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    function OK_Callback(hobject,eventdata)
        q_px(1,1) = str2num(get(bragg1x,'String'));
        q_px(2,1) = str2num(get(bragg1y,'String'));
        q_px(1,2) = str2num(get(bragg2x,'String'));
        q_px(2,2) = str2num(get(bragg2y,'String'));
        q_px(1,3) = str2num(get(bragg3x,'String'));
        q_px(2,3) = str2num(get(bragg3y,'String'));        
        filt_w = str2num(get(filt_width,'String'));
        
        phi_map = phase_map_hex(data.map,data.r,q_px,filt_w); 
        assignin('base','phase_map_test',phi_map); %added
        phi_map_cor = phase_slip_correct_dialogue_hex(phi_map);
%         phi_map_cor2 = fix_phase_the_manlyway(phi_map);
        assignin('base','phase_map',phi_map_cor);
%         assignin('base','phase_map2',phi_map_cor2);
        [tx ty] = LF_coordinates_hex2(1,filt_w,phi_map_cor,data);
        new_data = LF_correct_map_v2(tx,ty,data);      
        new_data.tx = tx; new_data.ty = ty;
        new_data.phase_map = phi_map_cor;
        img_obj_viewer2(new_data);
        display('New Data Created');
        close(fh);
    end
    function cancel_Callback(hObject,eventdata)       
        close(fh);
    end
end